/**
 * Source Registry - Defines all news and job sources
 */

export interface SourceConfig {
  name: string;
  type: 'rss' | 'api' | 'scraper';
  url: string;
  category: 'news' | 'jobs';
  subcategory?: string;
  reliabilityScore: number; // 0-100
  isPrimarySource: boolean;
  checkIntervalMinutes: number;
  config?: Record<string, unknown>;
  enabled: boolean;
}

// ================================
// News Sources
// ================================
export const newsSources: SourceConfig[] = [
  // Official AI Company Blogs (Primary Sources - High Reliability)
  {
    name: 'OpenAI Blog',
    type: 'rss',
    url: 'https://openai.com/blog/rss.xml',
    category: 'news',
    subcategory: 'ai',
    reliabilityScore: 95,
    isPrimarySource: true,
    checkIntervalMinutes: 60,
    enabled: true,
  },
  {
    name: 'Google AI Blog',
    type: 'rss',
    url: 'https://blog.google/technology/ai/rss/',
    category: 'news',
    subcategory: 'ai',
    reliabilityScore: 95,
    isPrimarySource: true,
    checkIntervalMinutes: 60,
    enabled: true,
  },
  {
    name: 'Anthropic News',
    type: 'rss',
    url: 'https://www.anthropic.com/news/rss',
    category: 'news',
    subcategory: 'ai',
    reliabilityScore: 95,
    isPrimarySource: true,
    checkIntervalMinutes: 60,
    enabled: true,
  },
  
  // Developer Platforms
  {
    name: 'GitHub Blog',
    type: 'rss',
    url: 'https://github.blog/feed/',
    category: 'news',
    subcategory: 'programming',
    reliabilityScore: 90,
    isPrimarySource: true,
    checkIntervalMinutes: 60,
    enabled: true,
  },
  {
    name: 'Dev.to',
    type: 'rss',
    url: 'https://dev.to/feed',
    category: 'news',
    subcategory: 'programming',
    reliabilityScore: 70,
    isPrimarySource: false,
    checkIntervalMinutes: 30,
    enabled: true,
  },
  
  // Cloud Providers
  {
    name: 'AWS News Blog',
    type: 'rss',
    url: 'https://aws.amazon.com/blogs/aws/feed/',
    category: 'news',
    subcategory: 'cloud',
    reliabilityScore: 95,
    isPrimarySource: true,
    checkIntervalMinutes: 60,
    enabled: true,
  },
  {
    name: 'Azure Updates',
    type: 'rss',
    url: 'https://azure.microsoft.com/en-us/blog/feed/',
    category: 'news',
    subcategory: 'cloud',
    reliabilityScore: 95,
    isPrimarySource: true,
    checkIntervalMinutes: 60,
    enabled: true,
  },
  {
    name: 'Google Cloud Blog',
    type: 'rss',
    url: 'https://cloud.google.com/blog/rss',
    category: 'news',
    subcategory: 'cloud',
    reliabilityScore: 95,
    isPrimarySource: true,
    checkIntervalMinutes: 60,
    enabled: true,
  },
  
  // Tech News Publications
  {
    name: 'Hacker News',
    type: 'api',
    url: 'https://hacker-news.firebaseio.com/v0',
    category: 'news',
    subcategory: 'general',
    reliabilityScore: 75,
    isPrimarySource: false,
    checkIntervalMinutes: 30,
    config: {
      minScore: 100, // Only fetch stories with 100+ points
      maxItems: 30,
    },
    enabled: true,
  },
  {
    name: 'TechCrunch',
    type: 'rss',
    url: 'https://techcrunch.com/feed/',
    category: 'news',
    subcategory: 'startup',
    reliabilityScore: 80,
    isPrimarySource: false,
    checkIntervalMinutes: 30,
    enabled: true,
  },
  {
    name: 'The Verge Tech',
    type: 'rss',
    url: 'https://www.theverge.com/tech/rss/index.xml',
    category: 'news',
    subcategory: 'general',
    reliabilityScore: 80,
    isPrimarySource: false,
    checkIntervalMinutes: 30,
    enabled: true,
  },
  {
    name: 'Ars Technica',
    type: 'rss',
    url: 'https://feeds.arstechnica.com/arstechnica/technology-lab',
    category: 'news',
    subcategory: 'general',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 30,
    enabled: true,
  },
  
  // Security Sources
  {
    name: 'Krebs on Security',
    type: 'rss',
    url: 'https://krebsonsecurity.com/feed/',
    category: 'news',
    subcategory: 'security',
    reliabilityScore: 90,
    isPrimarySource: false,
    checkIntervalMinutes: 60,
    enabled: true,
  },
  {
    name: 'The Hacker News',
    type: 'rss',
    url: 'https://feeds.feedburner.com/TheHackersNews',
    category: 'news',
    subcategory: 'security',
    reliabilityScore: 80,
    isPrimarySource: false,
    checkIntervalMinutes: 30,
    enabled: true,
  },
  
  // JavaScript/Web
  {
    name: 'JavaScript Weekly',
    type: 'rss',
    url: 'https://javascriptweekly.com/rss/',
    category: 'news',
    subcategory: 'webdev',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  {
    name: 'React Blog',
    type: 'rss',
    url: 'https://react.dev/rss.xml',
    category: 'news',
    subcategory: 'webdev',
    reliabilityScore: 95,
    isPrimarySource: true,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  
  // Mobile
  {
    name: 'Android Developers Blog',
    type: 'rss',
    url: 'https://android-developers.googleblog.com/feeds/posts/default',
    category: 'news',
    subcategory: 'mobile',
    reliabilityScore: 95,
    isPrimarySource: true,
    checkIntervalMinutes: 120,
    enabled: true,
  },
];

// ================================
// Job Sources (Including Fresher/Entry-Level, HR/Recruitment)
// ================================
export const jobSources: SourceConfig[] = [
  // ========== PRIMARY JOB BOARDS (APIs) ==========
  {
    name: 'RemoteOK',
    type: 'api',
    url: 'https://remoteok.com/api',
    category: 'jobs',
    reliabilityScore: 80,
    isPrimarySource: false,
    checkIntervalMinutes: 60,
    config: {
      filterTags: ['developer', 'engineer', 'programming', 'devops', 'design', 'junior', 'entry', 'hr', 'recruiter'],
    },
    enabled: true,
  },
  {
    name: 'Remotive',
    type: 'api',
    url: 'https://remotive.com/api/remote-jobs',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 60,
    enabled: true,
  },
  {
    name: 'Remotive HR Jobs',
    type: 'api',
    url: 'https://remotive.com/api/remote-jobs?category=hr',
    category: 'jobs',
    subcategory: 'hr',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  {
    name: 'Arbeitnow',
    type: 'api',
    url: 'https://www.arbeitnow.com/api/job-board-api',
    category: 'jobs',
    reliabilityScore: 75,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  
  // ========== RSS JOB FEEDS ==========
  {
    name: 'We Work Remotely - Programming',
    type: 'rss',
    url: 'https://weworkremotely.com/categories/remote-programming-jobs.rss',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 60,
    enabled: true,
  },
  {
    name: 'We Work Remotely - Full Stack',
    type: 'rss',
    url: 'https://weworkremotely.com/categories/remote-full-stack-programming-jobs.rss',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 60,
    enabled: true,
  },
  {
    name: 'We Work Remotely - Frontend',
    type: 'rss',
    url: 'https://weworkremotely.com/categories/remote-front-end-programming-jobs.rss',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 60,
    enabled: true,
  },
  {
    name: 'We Work Remotely - Backend',
    type: 'rss',
    url: 'https://weworkremotely.com/categories/remote-back-end-programming-jobs.rss',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 60,
    enabled: true,
  },
  {
    name: 'We Work Remotely - DevOps',
    type: 'rss',
    url: 'https://weworkremotely.com/categories/remote-devops-sysadmin-jobs.rss',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 60,
    enabled: true,
  },
  {
    name: 'We Work Remotely - All',
    type: 'rss',
    url: 'https://weworkremotely.com/remote-jobs.rss',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 60,
    enabled: true,
  },
  {
    name: 'Remote.co Jobs',
    type: 'rss',
    url: 'https://remote.co/remote-jobs/developer/feed/',
    category: 'jobs',
    reliabilityScore: 80,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  {
    name: 'Jobspresso Remote',
    type: 'rss',
    url: 'https://jobspresso.co/remote-jobs/feed/',
    category: 'jobs',
    reliabilityScore: 80,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  {
    name: 'Himalayas Remote',
    type: 'rss',
    url: 'https://himalayas.app/jobs/rss',
    category: 'jobs',
    subcategory: 'worldwide',
    reliabilityScore: 80,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  {
    name: 'Working Nomads',
    type: 'rss',
    url: 'https://www.workingnomads.com/jobs/rss',
    category: 'jobs',
    subcategory: 'remote',
    reliabilityScore: 75,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  {
    name: 'FlexJobs Tech',
    type: 'rss', 
    url: 'https://www.flexjobs.com/rss/jobs-it-computer',
    category: 'jobs',
    subcategory: 'remote',
    reliabilityScore: 80,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  {
    name: 'JustRemote Developer',
    type: 'rss',
    url: 'https://justremote.co/remote-developer-jobs/rss',
    category: 'jobs',
    subcategory: 'fresher',
    reliabilityScore: 75,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  
  // ========== HN WHO IS HIRING ==========
  {
    name: 'HN Who Is Hiring',
    type: 'api',
    url: 'https://hacker-news.firebaseio.com/v0',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 240,
    config: {
      type: 'whoishiring',
    },
    enabled: true,
  },
  
  // ========== INDEED RSS (Remote Jobs) ==========
  {
    name: 'Indeed Remote Software',
    type: 'rss',
    url: 'https://www.indeed.com/rss?q=remote+software+developer&l=&remotejob=032b3046-06a3-4876-8dfd-474eb5e7ed11&fromage=1',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  {
    name: 'Indeed Remote Frontend',
    type: 'rss',
    url: 'https://www.indeed.com/rss?q=remote+frontend+developer&l=&remotejob=032b3046-06a3-4876-8dfd-474eb5e7ed11&fromage=1',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  {
    name: 'Indeed Remote Backend',
    type: 'rss',
    url: 'https://www.indeed.com/rss?q=remote+backend+developer&l=&remotejob=032b3046-06a3-4876-8dfd-474eb5e7ed11&fromage=1',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  {
    name: 'Indeed Remote DevOps',
    type: 'rss',
    url: 'https://www.indeed.com/rss?q=remote+devops+engineer&l=&remotejob=032b3046-06a3-4876-8dfd-474eb5e7ed11&fromage=1',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  {
    name: 'Indeed Remote Data Engineer',
    type: 'rss',
    url: 'https://www.indeed.com/rss?q=remote+data+engineer&l=&remotejob=032b3046-06a3-4876-8dfd-474eb5e7ed11&fromage=1',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  {
    name: 'Indeed Junior Developer',
    type: 'rss',
    url: 'https://www.indeed.com/rss?q=junior+developer+remote&l=&remotejob=032b3046-06a3-4876-8dfd-474eb5e7ed11&fromage=1',
    category: 'jobs',
    subcategory: 'fresher',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  {
    name: 'Indeed Entry Level Developer',
    type: 'rss',
    url: 'https://www.indeed.com/rss?q=entry+level+developer+remote&l=&remotejob=032b3046-06a3-4876-8dfd-474eb5e7ed11&fromage=1',
    category: 'jobs',
    subcategory: 'fresher',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  
  // ========== INDEED HR/RECRUITMENT ==========
  {
    name: 'Indeed Remote HR',
    type: 'rss',
    url: 'https://www.indeed.com/rss?q=remote+hr+recruiter&l=&remotejob=032b3046-06a3-4876-8dfd-474eb5e7ed11&fromage=1',
    category: 'jobs',
    subcategory: 'hr',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  {
    name: 'Indeed Technical Recruiter',
    type: 'rss',
    url: 'https://www.indeed.com/rss?q=remote+technical+recruiter&l=&remotejob=032b3046-06a3-4876-8dfd-474eb5e7ed11&fromage=1',
    category: 'jobs',
    subcategory: 'hr',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  {
    name: 'Indeed Talent Acquisition',
    type: 'rss',
    url: 'https://www.indeed.com/rss?q=remote+talent+acquisition&l=&remotejob=032b3046-06a3-4876-8dfd-474eb5e7ed11&fromage=1',
    category: 'jobs',
    subcategory: 'hr',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    enabled: true,
  },
  
  // ========== LINKEDIN JOB RSS/FEEDS (Public Endpoints) ==========
  {
    name: 'LinkedIn Software Engineer',
    type: 'api',
    url: 'https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?keywords=software%20engineer&location=remote&f_WT=2&start=0',
    category: 'jobs',
    reliabilityScore: 90,
    isPrimarySource: true,
    checkIntervalMinutes: 120,
    config: {
      platform: 'linkedin',
      maxResults: 50,
    },
    enabled: true,
  },
  {
    name: 'LinkedIn Junior Developer',
    type: 'api',
    url: 'https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?keywords=junior%20developer&location=remote&f_WT=2&f_E=2&start=0',
    category: 'jobs',
    subcategory: 'fresher',
    reliabilityScore: 90,
    isPrimarySource: true,
    checkIntervalMinutes: 120,
    config: {
      platform: 'linkedin',
      maxResults: 50,
    },
    enabled: true,
  },
  {
    name: 'LinkedIn HR Recruiter',
    type: 'api',
    url: 'https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?keywords=hr%20recruiter&location=remote&f_WT=2&start=0',
    category: 'jobs',
    subcategory: 'hr',
    reliabilityScore: 90,
    isPrimarySource: true,
    checkIntervalMinutes: 120,
    config: {
      platform: 'linkedin',
      maxResults: 50,
    },
    enabled: true,
  },
  
  // ========== GLASSDOOR ==========
  {
    name: 'Glassdoor Remote Developer',
    type: 'api',
    url: 'https://www.glassdoor.com/Job/remote-software-developer-jobs-SRCH_IL.0,6_IS14748_KO7,25.htm',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 240,
    config: {
      platform: 'glassdoor',
    },
    enabled: true,
  },
  
  // ========== STARTUP/TECH SPECIFIC ==========
  {
    name: 'AngelList/Wellfound',
    type: 'api',
    url: 'https://wellfound.com/role/l/software-engineer/remote',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    config: {
      platform: 'wellfound',
    },
    enabled: true,
  },
  {
    name: 'Turing Remote Jobs',
    type: 'api',
    url: 'https://www.turing.com/remote-developer-jobs',
    category: 'jobs',
    reliabilityScore: 80,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    config: {
      platform: 'turing',
    },
    enabled: true,
  },
  {
    name: 'Toptal Jobs',
    type: 'api',
    url: 'https://www.toptal.com/careers',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: false,
    checkIntervalMinutes: 240,
    config: {
      platform: 'toptal',
    },
    enabled: true,
  },
  {
    name: 'Arc.dev Remote',
    type: 'api',
    url: 'https://arc.dev/remote-jobs',
    category: 'jobs',
    reliabilityScore: 80,
    isPrimarySource: false,
    checkIntervalMinutes: 120,
    config: {
      platform: 'arc',
    },
    enabled: true,
  },
  
  // ========== INDIA SPECIFIC (Naukri, etc.) ==========
  {
    name: 'Naukri Remote Developer',
    type: 'api',
    url: 'https://www.naukri.com/software-developer-jobs?wfhType=2',
    category: 'jobs',
    reliabilityScore: 85,
    isPrimarySource: true,
    checkIntervalMinutes: 120,
    config: {
      platform: 'naukri',
      region: 'india',
    },
    enabled: true,
  },
  {
    name: 'Naukri Fresher Developer',
    type: 'api',
    url: 'https://www.naukri.com/fresher-software-developer-jobs?wfhType=2&experience=0',
    category: 'jobs',
    subcategory: 'fresher',
    reliabilityScore: 85,
    isPrimarySource: true,
    checkIntervalMinutes: 120,
    config: {
      platform: 'naukri',
      region: 'india',
    },
    enabled: true,
  },
  {
    name: 'Naukri HR Jobs',
    type: 'api',
    url: 'https://www.naukri.com/hr-recruiter-jobs?wfhType=2',
    category: 'jobs',
    subcategory: 'hr',
    reliabilityScore: 85,
    isPrimarySource: true,
    checkIntervalMinutes: 120,
    config: {
      platform: 'naukri',
      region: 'india',
    },
    enabled: true,
  },
  
  // ========== ADDITIONAL PLATFORMS ==========
  {
    name: 'Authentic Jobs',
    type: 'rss',
    url: 'https://authenticjobs.com/rss/index.xml',
    category: 'jobs',
    reliabilityScore: 75,
    isPrimarySource: false,
    checkIntervalMinutes: 240,
    enabled: true,
  },
  {
    name: 'Dribbble Jobs',
    type: 'rss',
    url: 'https://dribbble.com/jobs.rss',
    category: 'jobs',
    subcategory: 'design',
    reliabilityScore: 75,
    isPrimarySource: false,
    checkIntervalMinutes: 240,
    enabled: true,
  },
  {
    name: 'Crypto Jobs List',
    type: 'rss',
    url: 'https://cryptojobslist.com/feed.xml',
    category: 'jobs',
    subcategory: 'blockchain',
    reliabilityScore: 70,
    isPrimarySource: false,
    checkIntervalMinutes: 240,
    enabled: true,
  },
  {
    name: 'AI Jobs',
    type: 'rss',
    url: 'https://aijobs.net/rss',
    category: 'jobs',
    subcategory: 'ai',
    reliabilityScore: 75,
    isPrimarySource: false,
    checkIntervalMinutes: 240,
    enabled: true,
  },
];

// All sources combined
export const allSources: SourceConfig[] = [...newsSources, ...jobSources];

// Get active sources by category
export function getActiveSources(category: 'news' | 'jobs'): SourceConfig[] {
  return allSources.filter(s => s.category === category && s.enabled);
}

// Get sources by subcategory
export function getSourcesBySubcategory(subcategory: string): SourceConfig[] {
  return allSources.filter(s => s.subcategory === subcategory && s.enabled);
}
